### ISSUE TITLE
"Assignment to constant variable" error when using useCylinder 

### ISSUE THREAD

**Issue by nevernotsean** [react-spring/use-cannon#11]
When using useCylinder body and collide with a sphere, getting a "Assignment to constant variable" error. Looks like a for loop is using "const" instead of "let" as the assignment for an iterator. Might be an issue with cannon-es?

**Comment by drcmda** [comment]
most likely, could you look into it? you should have full access to cannon-es. i converted cannon with lebab which turns es5 into 6, could well be it used a const in the wrong place. in the worst case we can turn all const into let and be done with it.

**Comment by nevernotsean** [comment]
@drcmda allset, fixed and merged. I don't have access to the npm registry so it hasn't been published yet. #

**Comment by drcmda** [comment]
whats your npm username?
