### ISSUE TITLE
Invalid path to type declarations in package.json

### ISSUE THREAD

**Issue by codynova** [react-spring/use-cannon#13]
The "types" field in package.json point to `dist/types.d.ts` rather than `dist/index.d.ts`.

Unrelated, but the type declarations for the Physics component return a React.ReactNode - but I believe it should be returning a JSX.Element.

**Comment by codynova** [comment]
It seems this is simply the error that occurs when typings are not found for the module. I plan to generate typings with tsc emit declarations.

**Comment by codynova** [comment]
I closed this issue because I thought use-cannon didn't ship with type declarations at all. However I can now see that there is an `index.d.ts` file in the `dist` directory - but the `types` field in package.json is (presumably) incorrect. I've submitted PR #16 to address this issue.

**Comment by codynova** [comment]
Unrelated to missing type declarations, but related to TypeScript issues and changes - I believe the Physics component should be returning a JSX.Element rather than a React.ReactNode. I've updated PR #16 with this change as well

**Comment by drcmda** [comment]
i'll publish a quick patch version for this

**Comment by codynova** [comment]
@drcmda Perfect, thank you very much. I realized I forgot to update the README, let me know if you'd like me to do so. I'm also working on a wireframe renderer for debugging.

**Comment by drcmda** [comment]
do you know your way around this, physics based stuff, etc? you could have github access, right now its @nevernotsean @stockHuman and me. it would be nice to let developers shape it that understand what they're doing - i for sure don't, but i can sure help digging in b/c i need this lib, too.

**Comment by codynova** [comment]
Yes, somewhat. I have some 3d experience from my [past work](https://www.youtube.com/watch?v=ipLfyPUu59c&t=4s) in the Unity Editor and similar 3d+physics environments. I've also done some stuff with depth data like integrating with Microsoft Kinect. Lately I have been using a lot of react-three-fiber and Cannon at work. I spent a good amount of time trying to clean up Cannon and improve/complete the type declarations. I have a couple public repositories available on this github account that may give you a feel for my code. You may also have seen me around on the react-spring and react-three-fiber spectrum chats.

I would love to be involved with shaping the lib, but I do have a bit of anxiety about it - I want to make sure that I can make actual useful contributions. You have a proven track record of releasing and supporting open source projects, and I lack that experience. However I do have a couple of ideas about things I would like to see added, like the wireframe renderer for debugging, and perhaps a `Capsule` class (although a "capsule" could easily be created using a compound shape that is a cylinder with a sphere glued to either end). I am certainly interested in contributing in whatever way would be most beneficial to the project.

**Comment by drcmda** [comment]
that is a thousand times more than i ever did with physics related projects. 👍 and don't worry, i really dislike when open source or managed source in general is so strict and rigid that people are scared to make mistakes. make a mistake and we roll something back, it's no big deal. if you like make pr's to be safe, or discuss ideas and prototypes first.

**Comment by nevernotsean** [comment]
Just chiming in to say that I'm not at all an expert on physics either, just happy to contribute. So you're in good company @codynova ;)

**Comment by stockHuman** [comment]
Also gonna chime and say most of my physics experience has been in the context of work by the giants whose shoulders I stood on - and also _not_ in javascript. Also-also, this is a really sweet social vibe to be working in. Sorry for not being as involved as I could be

**Comment by codynova** [comment]
Awesome, thank you all very much for the warm welcome. I look forward to contributing

**Comment by codynova** [comment]
Resolved in #16, released in v0.1.5
