### ISSUE TITLE
Questions: How much should worker handle CANNON related tasks?

### ISSUE THREAD

**Issue by nevernotsean** [react-spring/use-cannon#17]
This is an open question, I'm looking for a better understanding on everyones opinions on the worker. Should the worker behave as an automated creator of all the CANNON related classes other than just the bodies? Or should those class instances be the responsibility of the React component?

For instance, another class from Cannon is a physics material that can be customized to have different friction/slippery-ness. The way I see it, adding this ability could be either:

A) I am able to use a hook (i.e. useMaterial) in my component which 1. creates a new Cannon material, 2. adds it to the world list of materials then 3. applies that material to the specified body. The benefit here is that the developer doesn't have to mess with any Cannon classes, just the hooks.

B) In my project, I create a Cannon Material that adds itself to the Cannon world on init. Then in my component, I refer to that Cannon Material when creating a new Body. The benefit here is that I can create Materials in a separate file and refer to it in the world material list for re-use.

Some other classes would be Springs, Constraints, and ContactMaterials.

I'm just open to discussion and hearing what you guys think.
I think option B would be ready with #15, but option A would take managing of these lists off of the developer.

**Comment by drcmda** [comment]
can it be a simple parameter for useBody? like useBox({ mass: 1, material: { friction: something } ... sorry for the dumb question, never heard of cannon.material before, but now it makes sense.

**Comment by nevernotsean** [comment]
It sure could! I think that falls closer option A but is even simpler than what I had in mind and I'm all for it.

**Comment by nevernotsean** [comment]
Closing this, having a world instance in the main thread and the worker is too expensive.
