### ISSUE TITLE
Collision Events

### ISSUE THREAD

**Issue by nevernotsean** [react-spring/use-cannon#18]
Expose collision handler. An "onCollide" argument would be easy, with the worker adding and removing the handler on mount/unmount.

**Comment by nevernotsean** [comment]
Hey @drcmda I creating a working AddCollision hook, see here 
https://github.com/nevernotsean/use-cannon/tree/collision-events

It uses the library Comlink to setup proxies of the callbacks for both the worker and the main thread. I would implement my own ES6 proxies but I couldn't wrap my head around it.

One thing that I can't seem to figure out is to properly provide an return function for useEffect when the component unmounts (to call body.removeEventListener) bcs typescript was giving me issues.

Thoughts?

**Comment by drcmda** [comment]
i wonder why you went for an extra hook? why not useBox/Sphere/Etc(() => ({ onCollide: e => ... })) ?

in a variant i made for testing i simply created a bridge event, i didnt use comlink. should i try to remake it again so we could evaluate? i deleted it locally unfortunately.

**Comment by drcmda** [comment]
here's my resurrected event bridge: https://github.com/react-spring/use-cannon/pull/23

**Comment by nevernotsean** [comment]
Yeah, when I tried to include as an argument, (onCollide: () => {...}) I kept getting a DATA_CLONE_ERR. I'll take a look at your try in a sec.

**Comment by drcmda** [comment]
functions cant be transmitted. basically it has to store the function on the main thread, and the worker just forwards the information that something got hit.

**Comment by nevernotsean** [comment]
I took a look at the branch, it looks good!

**Comment by nevernotsean** [comment]
merged!

**Comment by drcmda** [comment]
ive made an awesome game example for collide :-D just needs some cleanup but looking really nice
