### ISSUE TITLE
Add collision filter groups and masks

### ISSUE THREAD

**Issue by nevernotsean** [react-spring/use-cannon#19]
This will let us define certain groups of bodies and limit what groups can collide with eachother.
Cannon demo here: http://schteppe.github.io/cannon.js/demos/collisionFilter.html
Source: https://github.com/schteppe/cannon.js/blob/master/demos/collisionFilter.html

In the example, we have a scene with a box, a sphere and a cylinder, with boxes ignoring collisions with the cylinder.

Layers are defined as bitwise operations (integers with a power of two)

We could use these layers in new 'collisionFilterGroup' and 'collisionFilterMask' arguments in useBody.

In the long run, some helper methods that solve using multiple groups on a single body would be super helpful and easy to implement. This concepts are similar in Unity's "LayerMasks" class and doing checks on them involve bitwise operators, if that helps.

**Comment by codynova** [comment]
Hey, I'd be happy to take a stab at this. I see how collision filters work in Cannon. What sort of helper methods do you have in mind?

**Comment by nevernotsean** [comment]
We might want to check layers during collision callback. For instance, I have a bullet and it can collide with everything, but I only want something to happen when the bullet hits a body with the PLAYER group.

**Comment by codynova** [comment]
I've exposed the collision layer data for both bodies on the "collide" event #25 

This should allow you to take an action on specific types of collisions.

**Comment by codynova** [comment]
#25 merged, closing

**Comment by codynova** [comment]
I renamed the `collisionGroups` key to the more accurate `collisionFilters`
