### ISSUE TITLE
ForwardRef and body hooks

### ISSUE THREAD

**Issue by Splact** [react-spring/use-cannon#27]
What's the best practice when a component with forwardRef needs to use a body hook like `useBox`?

```js
const` Model = forwardRef((props, ref) => {
  // ...
  const [cannonRef, api] = useBox(() => ({ mass: 1 }));
  // ...

  // How can I use cannonRef while I need to use ref coming from forwardRef?
  
  return (
    <mesh ref={ref}>
      {/* ... */}
    </mesh>
  );
});
```

Is there a way to pass an initial ref to `useBox()`?

eg.
```js
const [cannonRef, api] = useBox(() => ({ mass: 1, ref }));
```

**Comment by drcmda** [comment]
i would use https://github.com/smooth-code/react-merge-refs

**Comment by codynova** [comment]
In the case of passthrough, how would the returned ref be constructed? Is it a union of Three.Object3D and whatever is passed in?

**Comment by nevernotsean** [comment]
Hey @drcmda and @codynova, I'm curious about the passthrough option as well. Any thoughts on how that would be done? Currently I have merge-refs working for a use-cannon example, but wondering how this could work without adding another dependancy.

**Comment by drcmda** [comment]
passthrough works like this:

```jsx
function useSomething({ ref, ...props }) {
  const localRef = useRef()
  const actualRef = ref ? ref : localRef
  ...
  return actualRef
}
```

i've been using this for a couple of libs now, react-use-measure for instance does this.

**Comment by codynova** [comment]
Would we need a check to prevent passing a THREE.Object3D ref, so that the properties of the passed ref aren't overwritten?

**Comment by drcmda** [comment]
Not sure i understand, refs will always point to object3d's, even through forwardRef. But i don't know what spring and constraints will do, if both <Plane/> and <Box/> are already driven by use-cannon, then i guess useSpring/Constraint(planeRef, boxRef) should communicate its contract between the two without mutating anything - usePlane and useBox, the hooks that drive these object3d's should receive altered values from the web worker which has set up new conditions.

**Comment by nevernotsean** [comment]
#38 created

**Comment by drcmda** [comment]
looking good! also the spring demo. is it normal though that it never stops spinning?

**Comment by nevernotsean** [comment]
Ah, thats because of the default `linearDamping` value of the attached bodies. Cannon makes the default 0.1, but setting it higher feels more realistic.

**Comment by codynova** [comment]
Closing
