### ISSUE TITLE
Proposal: Replace api.setPosition and api.setRotation to api.set(obj)

### ISSUE THREAD

**Issue by nevernotsean** [react-spring/use-cannon#31]
Taking a page from RTF, making a shorthand set would have the same functionality as setting position and rotation, but open up any other property to be changed with the api too. E.g. I need to set the velocity to 0. Instead of creating new worker operators and api methods, just use { velocity: [0,0,0] } as the set parameter. Adding types to the worker may make this easier to reason about.

Will work on a PR today to try this out.

**Comment by nevernotsean** [comment]
Related to #28

**Comment by drcmda** [comment]
just dont forget instancing. i initially went for setXyz and setXyzAt to make it clear that one is single and the other is instanced. may be harder with just an object but havent thought much about it.

**Comment by drcmda** [comment]
maybe

```jsx
api.set({ ... })
api.setAt(10, { ... })
```

**Comment by drcmda** [comment]
i tried to look into it today, i think set is going to be complex for all the new stuff that's in there now. applyForce/Impulse/etc. Most of these need two specific argument, like:

```jsx
applyForce(force: [number, number, number], worldPoint: [number, number, number])
applyLocalForce(force: [number, number, number], localPoint: [number, number, number])
```

i wonder how that would go in a mere object 🤔

```jsx
set({ force: [...], worldPoint: [...] })
setAt(100, { force: [...], worldPoint: [...] })
```

seems a bit arbitrary to me, like the connection between these is a little too implicit for my taste. also it would force users to learn apis, instead of hitting "." and the IDE gives you the commands. but i do like the idea of set/setAt because we would have to double all these commands for instanced usage, which would suck. anyone has an idea how we could solve this?

**Comment by nevernotsean** [comment]
My thought was to use .set({...}) as a way to change body properties like position, rotation, etc. 

Body methods like applyForce and applyImpulse would not be replaced by .set(), they should be the primary way to move physics bodies around. Setting a property such as velocity or angularVelocity is more like an escape hatch, ignoring the physics simulation and should only be used in certain cases. 

Here's a use case, a body is moving extremely fast, and spinning out of control. Using applyForce alone would be fighting against the velocity. Using set I can stop the velocity, spin and lock the rotation, then apply my force.
```
api.set({
 velocity: [0,0,0],
 angularVelocity: [0,0,0]
 fixedRotation: true
})

api.applyForce([0,100,0], [0,0,0])
```
I do agree there might be a better way, having to learn how to use the api.set in order to tap into properties is a pain. Plus, workers are asynchronous, which makes getting any property value a race condition.
 
I have a branch with .set working, I'll push it if anyone wants to take a peek.

**Comment by drcmda** [comment]
another thing we could do is fake THREE.Vector3's in there, like:

```jsx
api.position.set(0,0,0)
api.position.copy(realVector3)
api.rotation.set(0,0,0)
api.rotation.copy(realEuler)
```

but, again, what about instancing. :-S this is such a hard case to get right - im already at my wits end.

**Comment by drcmda** [comment]
```jsx
const [ref, api] = useXyz()

api.position.set(0,0,0)
api.appyForce(...)

api.at(100, instancedApi => {
  instancedApi.rotation.set(0,0,0))
  instancedApi.appyForce(...)
})
```

🤔

**Comment by nevernotsean** [comment]
api.at() isn't too bad, very promising :+1:

**Comment by bvkimball** [comment]
How can you set the velocity -> x, y, or z properties independently?
Also is it possible to get the velocity from the worker?

**Comment by drcmda** [comment]
api.velocity.set(x,y,z), also has .copy(Vector3/Euler) available. Reading isn't possible atm and would have to be async, you'd get a promise back.

**Comment by codynova** [comment]
I believe this is all wrapped up since #37 and the switch to `makeApi`, closing
