### ISSUE TITLE
Option to set Cannon body to "Kinematic"

### ISSUE THREAD

**Issue by nevernotsean** [react-spring/use-cannon#4]
In PHYSX and Unity, rigid bodies have an option called "isKinematic". 

From the PhysX docs: 
`https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/RigidBodyDynamics.html#kinematic-actors`

> Each simulation step PhysX moves the actor to its target position, regardless of external forces, gravity, collision, etc. The actor will appear to have infinite mass and will push regular dynamic actors out of the way.

Example use case: I have a sphere that I want to animate with an animation loop (e.g. move position) and push away a bunch of boxes. Trying to do so with a Cannon body will mean the animation may be fighting against other forces. Turning off the Cannon Body would turn off the collisions. Setting a parameter such as isKinematic to true would solve both problems.

Does anyone else think this would be a good addition?

**Comment by drcmda** [comment]
sounds good!

**Comment by nevernotsean** [comment]
I didn't know this, but "Kinematic" is already a body type in Cannon, so a simple flag should be all that we need to add! I'll add this today.

Here's a demo: http://schteppe.github.io/cannon.js/demos/bodyTypes.html
and the property: http://schteppe.github.io/cannon.js/docs/classes/Body.html#property_type

**Comment by nevernotsean** [comment]
Added! Changed the example here to use a box with mass set to 1 and "isKinematic" instead of a box with mass 10000. The difference is slightly noticeable to me, the box looks rock solid when colliding with spheres.
