### ISSUE TITLE
Returned API incomplete? (setVelocity etc.)

### ISSUE THREAD

**Issue by christophfriedrich** [react-spring/use-cannon#44]
Hi, I like your project a lot and currently play around with it, but now I've come across a problem.

In my little game I want to throw a ball. The "How it works" section says:
> You can interact with [the object] by using the api, which lets you apply positions and rotations.

But, when I [scroll down](https://github.com/react-spring/use-cannon#returned-api), the docs promise more:

> ```typescript
> type WorkerApi = AtomicProps & {
>   position: WorkerVec
>   rotation: WorkerVec
>   velocity: WorkerVec
>   angularVelocity: WorkerVec
>   applyForce: (force: number[], worldPoint: number[]) => void
>   applyImpulse: (impulse: number[], worldPoint: number[]) => void
>   applyLocalForce: (force: number[], localPoint: number[]) => void
>   applyLocalImpulse: (impulse: number[], localPoint: number[]) => void
> }
> ```

Setting positions works perfectly, but there seems to be no e.g. `setVelocity` or `applyImpulse`. But for my use case I need these functions. (Don't I?)

Are they not implemented yet or am I missing something? (Before this project I have never done anything with React or Three.js, so sorry if my question is stupid... I use react-three-fiber and build upon Paul Henschel's pingpong mini-game.)

Thanks for your work!

**Comment by bvkimball** [comment]
if you look at the type def for `WorkerVec` you will see that you can set the velocity like so:
`api.velocity.set(1,1,1)`
and for impulse
`api.applyImpulse([1,1,1], [0,0,0])`

**Comment by christophfriedrich** [comment]
Trying that didn't work: "TypeError: api.velocity is undefined"

But I discovered that I was "still" (if you can say that, it's not even two weeks old 😅) on v0.2.0 -- after upgrading to the latest v0.2.6 that was just released everything's there as it should. So it was a mistake on my side 🙃

Thanks for the quick reply that opened my eyes!

**Comment by drcmda** [comment]
sorry for this - we figured that as long as this is still experimental (in that some details can still change if we find a better way) making major bumps would be wasteful. instead we stay 0.x.x until we have a fixed, defined api. then we go 1.x.x and from then on semver. you can of course all participate - if you dont like a particular api or have idea on how to do it better ...

**Comment by christophfriedrich** [comment]
"No worries" -- changing the API in whatever way you want is perfectly fine for a v0.x.x project that's experimental and as rapidly changing as this one. I won't complain when you're constantly improving stuff :D
I saw you already updated the dependency in your pingpong game codesandbox, so the next one to build off it won't have my issue but will use the (right now) latest cut -- nice! 🙂👍
