### ISSUE TITLE
spectrum for cannon-es and use-cannon

### ISSUE THREAD

**Issue by drcmda** [react-spring/use-cannon#52]
I've set up a spectrum: https://spectrum.chat/use-cannon would you all want to be in the team with admin rights? @nevernotsean @stockHuman @codynova I've been using spectrum for spring and r3f and it's a good tool to reserve github issues for bugs and enhancements and it helps to form a community. use-cannon is still small, but it has so much potential.

**Comment by codynova** [comment]
Sounds good to me, I've used spectrum for react-spring and rtf as well, and it's been a really good user experience

**Comment by drcmda** [comment]
i think you just need to join, then i can add you. we can also set up a small message here on github when people click "new issue"

**Comment by codynova** [comment]
Done. Can we set up the ability for team members to create issues in the `cannon-es` repo?

**Comment by drcmda** [comment]
You ... Can't open issues? How come?

**Comment by nevernotsean** [comment]
Joined, add me as an admin when you get a chance @drcmda

**Comment by drcmda** [comment]
done
