### ISSUE TITLE
Cylinder doesn't behave as expected

### ISSUE THREAD

**Issue by christophfriedrich** [react-spring/use-cannon#58]
When placing a cylinder on a surface it doesn't just stand there as expected but "sinks into the ground" or rolls around.

Example: https://codesandbox.io/s/amazing-proskuriakova-4slpq (shows the sink-into-the-ground bug; change the mass from 50000 to 5 to see the rolling around bug)

See also: [StackOverflow question](https://stackoverflow.com/q/60858561/3746543), [Spectrum thread](https://spectrum.chat/use-cannon/general/bug-with-a-cup-on-a-table~4575ca94-1d56-4298-89af-ca5173ba5a62)

**Comment by codynova** [comment]
I believe this is behaving as expected per the orientation of cylinders in Cannon. We should probably update `cannon-es` to be aligned with Three's cylinder. There is a solution that involves rotating all points in the shape around the axis at runtime - but that's considerably less performant

**Comment by codynova** [comment]
Moving to the cannon-es repo

https://github.com/react-spring/cannon-es/issues/13

**Comment by codynova** [comment]
@christophfriedrich This was finally resolved today (see https://github.com/react-spring/cannon-es/issues/13), and released in `use-cannon@0.4.5`
