### ISSUE TITLE
confusing rotation param in compound shapes 

### ISSUE THREAD

**Issue by Platane** [react-spring/use-cannon#60]
When using compound bodies, the rotation param is meant to be in quaternion form.

https://github.com/react-spring/use-cannon/blob/e9712e26d6323c5a47701d465d4111d2ed5950ba/src/worker.js#L159

afaik everywhere else it is supposed to be in euler form. For example for the compound root:
 https://github.com/react-spring/use-cannon/blob/e9712e26d6323c5a47701d465d4111d2ed5950ba/src/worker.js#L169 

This is a bit confusing. Is it unintentional ? If so I can PR

awesome work btw :+1:

**Comment by codynova** [comment]
That was indeed a mistake - I just noticed it myself this morning, and it's now fixed in `use-cannon@0.4.1`. Thank you, and we welcome any further contributions!
