### ISSUE TITLE
Typescript error on import

### ISSUE THREAD

**Issue by TheSonOfThomp** [react-spring/use-cannon#77]
I just included `use-cannon` in my project, and I'm immediately seeing a Typescript error:

```bash
TypeScript error in /path/to/node_modules/use-cannon/dist/hooks.d.ts(1,13):
'=' expected.  TS1005

  > 1 | import type { MaterialOptions, RayOptions } from 'cannon-es';
      |             ^
    2 | import type { Event } from './index';
    3 | import * as THREE from 'three';
    4 | import React from 'react';

```

**Comment by codynova** [comment]
What version of TypeScript are you using? You need `typescript@>=3.8.0`

**Comment by TheSonOfThomp** [comment]
Ah I’m on 3.7. Thanks. 
A little surprised I didn’t get a peer dependency warning, but that’s probably it

**Comment by codynova** [comment]
Good point, it's been added to peerDependencies and will release with the next update
