### ISSUE TITLE
Automatic collision bounding boxes for gltfjsx  mesh groups

### ISSUE THREAD

**Issue by rishabhaggarwal2** [react-spring/use-cannon#88]
Is there an easy way to get bounding boxes and useCannon on the different mesh groups returned by gltfjsx? Trying to make a game where the world is exported as a glb model and want to make the player collide with the different buildings / obstacles in the glb file.

**Comment by drcmda** [comment]
you can get bounds from the returned geometry https://threejs.org/docs/index.html#api/en/core/BufferGeometry.computeBoundingBox

**Comment by drcmda** [comment]
for more complex shapes where a box wouldnt be good enough use a venvexpolyhedron: https://github.com/react-spring/use-cannon/blob/master/examples/src/demos/ConvexPolyhedron.js

**Comment by rishabhaggarwal2** [comment]
Thanks for the quick response @drcmda 

So I tried the first step of loading the model in using gltfjsx and on my environment, I was get the scene variable to populate but nodes and materials were empty. Testing in codesandbox, all scene, nodes and material happen to be null for some reason. 

https://codesandbox.io/s/mystifying-cloud-8rm3k?file=/src/World2.js

**Comment by drcmda** [comment]
this sandbox is using an ancient r3f. all the node/material stuff didnt exist in version 3.
