### ISSUE TITLE
Expose CannonJS Ray with hook

### ISSUE THREAD

**Issue by nevernotsean** [react-spring/use-cannon#9]
Ray's are used in Cannon similarly to THREE's rays, but contain special collision data when it hits. I think a "useRay" hook would be nice for this.

**Comment by drcmda** [comment]
sounds useful!

**Comment by codynova** [comment]
I will try to look this weekend

**Comment by codynova** [comment]
Added new hooks in #47: `useRaycastClosest`, `useRaycastAny`, and `useRaycastAll`
