### ISSUE TITLE
Fails to compile on `npm start` with TypeScript support

### ISSUE THREAD

**Issue by mrlubos** [react-spring/use-cannon#93]
Hey! I am trying to run the basic example using `create-react-app` with the TypeScript template. I installed the latest `use-cannon` version (0.4.9), imported it using `import { Physics } from 'use-cannon'` and then hit `npm start`. This is what I get.

```
/root/node_modules/use-cannon/dist/hooks.d.ts
TypeScript error in /root/node_modules/use-cannon/dist/hooks.d.ts(1,13):
'=' expected.  TS1005

  > 1 | import type { MaterialOptions, RayOptions } from 'cannon-es';
      |             ^
    2 | import type { Event } from './index';
    3 | import * as THREE from 'three';
    4 | import React from 'react';
```

Are you able to help me debug what's going wrong please? Not sure if it's an issue with my setup or not

**Comment by codynova** [comment]
Hi @mrlubos, please check your TypeScript version against the project `peerDependencies`. You will need a version of TypeScript that supports type-only imports.

**Comment by mrlubos** [comment]
Hi @codynova, thank you for your help! I can confirm upgrading TypeScript from `3.7.2` to `3.9.7` fixed the issue.
