### ISSUE TITLE
hooks wont work in gatsby 

### ISSUE THREAD

**Issue by AidenFaulconer** [react-spring/use-cannon#97]
Hello, I am using use-cannon with react three fiber in the context of gatsby for my static site generation. When it compiles, it cannot find the react hooks and it registers them as an object when they need to be a function. Here is the code to reproduce this problem -> https://codesandbox.io/s/gatsby-react-three-fiber-frmxq?file=/src/pages/index.js:2327-2334

This issue seems to render use-cannon unusable with hooks in gatsby

**Comment by drcmda** [comment]
could you look into the source and tell us what we need to do? i know nothing about gatsby, we just use common everyday react hooks, useState, useRef, etc. i wouldnt know why gatsby makes objects out of that.

**Comment by AidenFaulconer** [comment]
> 
> 
> could you look into the source and tell us what we need to do? i know nothing about gatsby, we just use common everyday react hooks, useState, useRef, etc. i wouldnt know why gatsby makes objects out of that.

I found it was the versioning, setting my versions to the following fixed it. However, having the most up-to-date versions of each breaks it.

    "react-three-fiber": "5.0.0-beta.8",
    "three": "0.117.1",
    "use-cannon": "0.4.9"

**Comment by codynova** [comment]
@AidenFaulconer Could you narrow the issue down to one or two of those libraries? It sounds like a breaking change was made recently and I'd like to resolve it if possible
